# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
