# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songplay', '0004_auto_20161213_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
