# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songplay', '0005_request_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='down_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='up_diff',
            field=models.IntegerField(default=0),
        ),
    ]
