# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songplay', '0006_auto_20170226_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='down_diff',
            new_name='down_difference',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='up_diff',
            new_name='up_difference',
        ),
    ]
