# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songplay', '0007_auto_20170226_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='down_difference',
        ),
        migrations.RemoveField(
            model_name='request',
            name='up_difference',
        ),
        migrations.AddField(
            model_name='voterecord',
            name='down_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='up_difference',
            field=models.IntegerField(default=0),
        ),
    ]
